name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  main_project_module: app
  playstore_name: IIECat

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Run Gradle Tests
        run: ./gradlew test

      - name: Build Gradle Project
        run: ./gradlew build

      - name: Build APK Debug
        run: ./gradlew ${{ env.main_project_module }}:assembleDebug

      - name: Build APK Release
        run: ./gradlew ${{ env.main_project_module }}:assembleRelease

      - name: Build App Bundle (AAB) Release
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - APK Debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - APK Release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB Release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - AAB Release
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
